### ISSUE TITLE
Forever does not obey the current working directory properly

### ISSUE THREAD

**Issue by erulabs** [rackspace-cookbooks/nodestack#185]
It seems only very recently did foreverjs allow the "workingDir" option: https://github.com/foreverjs/forever/pull/627

This does not appear to work via options in the forever server.js file delivered by this template.

This means applications working directory when run is /var/app and not /var/app/current.

I have tried to solve this a number of ways and failed - instead I'll issue a patch which allows easier management of a custom startup command in the OS init scripts. For example, one customers application should start(even in production) with a "grunt", instead of a "forever /var/app/current/ENTRY_POINT". Some customers will bundle forever (or PM2) into the "grunt" or "gulp" tasks.

I'll issue a PR which adds a new deployment strategy as an alternative to "forever", called maybe "direct" which sets up the system init scripts for a custom command (like chdir /var/app/current ; gulp).

**Comment by marcoamorales** [comment]
Thanks for filing an issue.

Could you provide a way to replicate this problem?

You're probably having issues with forever taking the `workingDir` option because nodestack doesn't directly use [forever](https://github.com/foreverjs/forever), it uses [forever-monitor](https://github.com/foreverjs/forever-monitor).

Either way, a "direct" deployment strategy which just runs a custom command seems to me like a useful strategy that would further complement nodestack.

**Comment by erulabs** [comment]
I'm still trying to figure out exactly how my particular issue manifests itself. It's buried deep in Mongoose - but I believe It's a simple call to the __dirname global.

I've been researching ways aside from forever to alter the working directory in node. I am thinking I can solve this via the forever script with http://nodejs.org/api/process.html#process_process_chdir_directory

**Comment by erulabs** [comment]
It appears forever-monitor simply calls this option "cwd".

PR issued.
